# Generated by Django 5.1 on 2024-09-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_remove_profile_profile_image_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='dob',
        ),
    ]
